FROM tensorflow/tensorflow:latest-jupyter

RUN apt-get update && apt-get install -y python3-opencv

COPY requirements.txt .

RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt